Map data = {
  "yoga": [
    {
      "language": ["french", "spanish", "english", "russian"],
      "_id": "5eadb98cf59b195508430ef1",
      "url": "",
      "name": "angelina",
      "number": 7975782236,
      "gender": "female",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 5,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english"],
      "_id": "5eadb9daf59b195508430ef2",
      "url": "",
      "name": "obama",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 5,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef3",
      "url": "",
      "name": "bob",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef4",
      "url": "",
      "name": "abhishek",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 5,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef8",
      "url": "",
      "name": "moorthy",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef7",
      "url": "",
      "name": "kumar",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef5",
      "url": "",
      "name": "pascal",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef6",
      "url": "",
      "name": "amit",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430ef9",
      "url": "",
      "name": "nag",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430efa",
      "url": "",
      "name": "baskhar",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430efb",
      "url": "",
      "name": "param",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0
    },
    {
      "language": ["english", "hindi"],
      "_id": "5eadc31af59b195508430efc",
      "url": "",
      "name": "chay",
      "number": 7975782237,
      "gender": "male",
      "fitnesstype": "yoga",
      "free": "yes",
      "rating": 4,
      "price": 1000,
      "__v": 0,
    },
  ],
  "pilates": [
    {
      "language": ["marathi", "hindi", "english"],
      "_id": "5eadb8e1f59b195508430eef",
      "url": "",
      "name": "jaggu",
      "number": 7975782234,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 5,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["kannada", "hindi", "arabic", "english"],
      "_id": "5eadb929f59b195508430ef0",
      "url": "",
      "name": "anirudh",
      "number": 7975782235,
      "gender": "male",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 5,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f07",
      "url": "",
      "name": "chikoo",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 4,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f08",
      "url": "",
      "name": "sandoo",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 5,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f09",
      "url": "",
      "name": "mikoo",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 4,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f0a",
      "url": "",
      "name": "aldehyde",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 5,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f0b",
      "url": "",
      "name": "kuchoo",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 4,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f0c",
      "url": "",
      "name": "ketone",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 4,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f0d",
      "url": "",
      "name": "puchoo",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 5,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f0e",
      "url": "",
      "name": "mofo",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 4,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f0f",
      "url": "",
      "name": "alcohol",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 5,
      "price": 400,
      "__v": 0
    },
    {
      "language": ["english", "spanish", "tamil"],
      "_id": "5eadc545f59b195508430f10",
      "url": "",
      "name": "ester",
      "number": 7975782238,
      "gender": "female",
      "fitnesstype": "pilates",
      "free": "yes",
      "rating": 4,
      "price": 400,
      "__v": 0,
    },
  ],
  "athletic": [
    {
      "language": ["kannada", "hindi", "tamil", "english"],
      "_id": "5eadb858f59b195508430eed",
      "url": "",
      "name": "harsha",
      "number": 7975782232,
      "gender": "male",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 5,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["kannada", "telugu", "tamil", "english"],
      "_id": "5eadb887f59b195508430eee",
      "url": "",
      "name": "ikesh",
      "number": 7975782233,
      "gender": "male",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 4,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f00",
      "url": "",
      "name": "mia",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 5,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430efe",
      "url": "",
      "name": "moscow",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 5,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430efd",
      "url": "",
      "name": "margeret",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 4,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f01",
      "url": "",
      "name": "tokyo",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 5,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430eff",
      "url": "",
      "name": "berlin",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 5,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f02",
      "url": "",
      "name": "janaki",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 4,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f03",
      "url": "",
      "name": "monica",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 4,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f04",
      "url": "",
      "name": "denver",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 4,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f05",
      "url": "",
      "name": "dhruvi",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 5,
      "price": 300,
      "__v": 0
    },
    {
      "language": ["english", "telugu", "tamil"],
      "_id": "5eadc432f59b195508430f06",
      "url": "",
      "name": "harshi",
      "number": 7975782235,
      "gender": "female",
      "fitnesstype": "athletic",
      "free": "yes",
      "rating": 4,
      "price": 300,
      "__v": 0,
    },
  ],
  "weight management": [
    {
      "language": ["kannada", "hindi", "tamil", "english"],
      "_id": "5eadb7edf59b195508430eeb",
      "url": "",
      "name": "dhruva",
      "number": 7975782230,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 5,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["kannada", "tamil", "english"],
      "_id": "5eadb82bf59b195508430eec",
      "url": "",
      "name": "jerin",
      "number": 7975782231,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 5,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f11",
      "url": "",
      "name": "William",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 5,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f12",
      "url": "",
      "name": "Robert",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f13",
      "url": "",
      "name": "James",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f15",
      "url": "",
      "name": "Donald",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f14",
      "url": "",
      "name": "Mark",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 5,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f16",
      "url": "",
      "name": "Michael",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f17",
      "url": "",
      "name": "Christopher",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f18",
      "url": "",
      "name": "Paul",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f19",
      "url": "",
      "name": "David",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 4,
      "price": 250,
      "__v": 0
    },
    {
      "language": ["english", "german", "portuguese"],
      "_id": "5eadc69ff59b195508430f1a",
      "url": "",
      "name": "George",
      "number": 7975782239,
      "gender": "male",
      "fitnesstype": "weight management",
      "free": "yes",
      "rating": 5,
      "price": 250,
      "__v": 0,
    },
  ],
};
